CommunityTournaments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('Groups.urls'), name="groups"),
    path('', include('Profiles.urls'), name="profiles"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Groups/urls.py
from django.urls import path
from Groups import views


app_name = 'groups'
urlpatterns = [
    # ex: /betting/
    path('', views.groupsHome, name='home'),
    path('search/', views.groupSearch, name='groupSearch'),
    path('create/', views.createGroup, name='createGroup'),
    path('<int:group_id>/', views.group_page, name='groupPage'),
    path('<int:group_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts'),
    path('<int:group_id>/tournaments/<int:tournament_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts_tournament'),
    path('<int:group_id>/invite/<int:page>/', views.invitePage, name='invitePage'),
    path('<int:group_id>/admin/', views.adminPageOptions, name='adminPage'),
    path('<int:group_id>/admin/games/add/', views.adminPageAddGames, name='adminPageAddGames'),
    path('<int:group_id>/admin/tournaments/add/', views.adminPageAddTournament, name='adminPageAddTournament'),
    path('<int:group_id>/members/<int:page>/', views.groupMembers, name='groupMembers'),
    path('<int:group_id>/tournaments/', views.tournament_list_view, name='tournament_list_view'),
    path('<int:group_id>/tournaments/<int:tournament_id>/', views.tournament_view, name='tournament_view'),
    path('<int:group_id>/<int:betting_group_id>/', views.match_view, name='matchView'),
    path('<int:group_id>/completed-games/', views.completed_game_list_view, name='completed_games_list_view'),

]

Profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'
urlpatterns = [
    # ex: /betting/
    path('join/', views.landingPage, name='landingPage'),
    path('profile/', views.profile_details_default, name='profileDetailsDefault'),
    path('profile/<int:group_id>/', views.profile_details_group, name='profileDetailsGroup'),
]

Profiles/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from Groups.models import CommunityGroup
from django.templatetags.static import static
import random

# Create your models here.
User = settings.AUTH_USER_MODEL


def upload_location(instance, filename):

    location = instance.user.username
    return "%s/%s"%(location, filename)


def hex_to_rgb(colour):
    rgb_str = str((tuple(int(colour[i:i + 2], 16) for i in (0, 2, 4))))
    rgb_str = rgb_str.rstrip(")")
    rgb_str = rgb_str.lstrip("(")
    return rgb_str


def hex_to_rgb_whitened(colour):
    rgb_str = (tuple(int(colour[i:i + 2], 16) for i in (0, 2, 4)))
    white = (255, 255, 255)
    whitened_value = str(((rgb_str[0] + white[0]) / 2, (rgb_str[1] + white[1]) / 2, (rgb_str[2] + white[2]) / 2))
    whitened_value = whitened_value.rstrip(")")
    whitened_value = whitened_value.lstrip("(")
    return whitened_value

# The number of custom images held. Will allow users to randomly be assigned an image on sign_up
number_of_custom_images = 32


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    location = models.CharField(max_length=120, null=True, blank=True)
    nickname = models.CharField(max_length=20, null=True, blank=True)
    picture_id = models.IntegerField(default=1, null=False, blank=False)
    colour = models.CharField(max_length=7, null=False, blank=False, default="D3D3D3")
    groups = models.ManyToManyField(
        CommunityGroup,
        through='Wallet',
        through_fields=('profile', 'group'),
        related_name="groups_profile"
    )

    @property
    def picture_url(self):
        image = "img/profile_pictures/picture_" + str(self.picture_id) + ".png"
        return static(image)

    @property
    def colour_rgb(self):
        return hex_to_rgb(self.colour)

    @property
    def colour_rgb_whitened(self):
        return hex_to_rgb_whitened(self.colour)

    def __str__(self):
        return self.user.username


# TODO: Probable duplicate: Set colour/picture to match profile values on wallet creation
class Wallet(models.Model):
    profile = models.ForeignKey(Profile, related_name='profiles_wallet', blank=False, null=False, on_delete=models.PROTECT)
    group = models.ForeignKey(CommunityGroup, related_name='groups_wallet', blank=False, null=False, on_delete=models.PROTECT)
    withdrawable_bank = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    non_withdrawable_bank = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    nickname = models.CharField(max_length=20, null=True, blank=True)
    picture_id = models.IntegerField(default=1, null=False, blank=False)
    colour = models.CharField(max_length=7, null=False, blank=False, default="df2020")
    ranking = models.IntegerField(default=0)
    founder = models.BooleanField(default=False, blank=False, null=False)
    admin = models.BooleanField(default=False, blank=False, null=False)
    inviter = models.ForeignKey(Profile, related_name='inviters_wallet', blank=True, null=True, on_delete=models.PROTECT)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    active = "active"  # Active member of the group
    deactivated = "deactivated"  # A member who has left or been kicked out of the group
    sent = "sent"  # A user that has been invited to the group
    requesting_invite = "requesting_invite"  # A user that has requested an invited from a private group
    declined = "declined"  # A user that has had their request to join declined
    blocked_by_group = "blocked_by_group"  # A user that has been blocked by the group
    blocked_by_user = "blocked_by_user"  # Where a user has blocked a group from sending invites

    available_statuses = (
        (sent, "Sent"),
        (declined, "Declined"),
        (blocked_by_group, "Blocked by Group"),
        (blocked_by_user, "Blocked by User"),
        (active, "Active"),
        (deactivated, "Deactivated"),
        (requesting_invite, "Requesting Invite")
    )

    status = models.CharField(max_length=30,
                              choices=available_statuses,
                              default=active,
                              null=False,
                              blank=False)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Wallet, self).save(*args, **kwargs)

    @property
    def picture_url(self):
        image = "img/profile_pictures/picture_" + str(self.picture_id) + ".png"
        return static(image)

    @property
    def bank(self):
        return self.withdrawable_bank + self.non_withdrawable_bank

    @property
    def lifetime_winnings(self):
        bets = self.profile.user.user_bets.all()
        lifetime_winnings = 0
        for bet in bets:
            if bet.status == bet.paid:
                lifetime_winnings += bet.winnings
        return lifetime_winnings

    @property
    def colour_rgb(self):
        return hex_to_rgb(self.colour)

    @property
    def colour_rgb_whitened(self):
        return hex_to_rgb_whitened(self.colour)

    class Meta:
        unique_together = ('profile', 'group')

    def __str__(self):
        return str(self.profile.user.username) + "'s Wallet for: " + str(self.group.name)


class Team(models.Model):
    name = models.CharField(max_length=200, null=False)
    api_team_id = models.IntegerField(unique=True, null=True, blank=True)

    picture_id = models.IntegerField(default=1, null=False, blank=False)
    colour = models.CharField(max_length=7, null=False, blank=False, default="D3D3D3")

    @property
    def picture_url(self):
        image = "img/game_logos/logo_" + str(self.picture_id) + ".png"
        return static(image)

    @property
    def colour_rgb(self):
        return hex_to_rgb(self.colour)

    @property
    def colour_rgb_whitened(self):
        return hex_to_rgb_whitened(self.colour)

    def __str__(self):
        return self.name

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance, picture_id=random.randint(1, number_of_custom_images))

# Update the number of users in a community group after wallet creation
@receiver(post_save, sender=Wallet)
def update_number_of_community_users(sender, instance, created, **kwargs):
    if created:
        instance.picture_id = instance.profile.picture_id
        instance.save()

        community_group = instance.group
        number_of_users = len(community_group.groups_profile.all())
        community_group.total_number_users = number_of_users
        community_group.save()

Profiles/forms.py
from django import forms


class NicknameForm(forms.Form):
    nickname = forms.CharField(max_length=20)


class LocationForm(forms.Form):
    location = forms.CharField(max_length=120)


class ImageForm(forms.Form):
    picture_id = forms.IntegerField(required=True)


# TODO: Form validation for colours etc.
class ColourForm(forms.Form):
    colour_string = forms.CharField(max_length=7)

Profiles/views.py
from django.shortcuts import render, get_object_or_404
from Profiles.models import Wallet, Profile, number_of_custom_images
from django.http import Http404
from Groups.models import CommunityGroup
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.templatetags.staticfiles import static
from .forms import *
import colorsys

# Create your views here.
def landingPage(request):
    context = {

    }
    return render(request, 'profiles/landingPage.html', context)


# TODO: Set created wallets to the default profile values for colour, image, and nickname
# TODO: Set created profiles to random values for colour and image
# TODO: Wire up match + any group pages to use the wallet values for a user
# TODO: Ensure that an image and colour are required fields for both profile and wallet
# TODO: Make sure the group page and match page etc are using nicknames etc
@login_required(redirect_field_name="")
def profile_details_default(request):
    # Set user to request.user
    user = request.user

    wallets = user.profile.profiles_wallet.all()

    if request.method == "POST":
        if 'form_name' in request.POST:
            form_name = request.POST['form_name']

            if form_name == "set_default":
                # TODO: Add a popup in html/css/javascript asking the user if they're sure
                for wallet in wallets:
                    wallet.nickname = user.profile.nickname
                    wallet.colour = user.profile.colour
                    wallet.picture_id = user.profile.picture_id
                    wallet.save()
                    # TODO: add success messages and errors
            elif form_name == "nickname":
                if "delete_nickname" in request.POST:
                    if request.POST['delete_nickname']:
                        # Set all other groups data to the default values
                        user.profile.nickname = None
                        user.profile.save()
                else:
                    form_dict = {
                        "nickname": request.POST['nickname']
                    }
                    form = NicknameForm(form_dict)
                    if form.is_valid():
                        nickname = form.cleaned_data['nickname']
                        user.profile.nickname = nickname
                        user.profile.save()
            elif form_name == "location":
                if "delete_location" in request.POST:
                    if request.POST['delete_location']:
                        # Set all other groups data to the default values
                        user.profile.location = None
                        user.profile.save()
                else:
                    form_dict = {
                        "location": request.POST['location']
                    }
                    form = LocationForm(form_dict)
                    if form.is_valid():
                        location = form.cleaned_data['location']
                        user.profile.location = location
                        user.profile.save()
            elif form_name == "picture":
                form_dict = {
                    "picture_id": request.POST['picture_id']
                }
                form = ImageForm(form_dict)
                if form.is_valid():
                    picture_id = form.cleaned_data['picture_id']
                    user.profile.picture_id = picture_id
                    user.profile.save()
            elif form_name == "colour":
                form_dict = {
                    "colour_string": request.POST['colour_string']
                }
                form = ColourForm(form_dict)
                if form.is_valid():
                    colour_string = form.cleaned_data['colour_string']
                    colour_string = colour_string[1:]
                    user.profile.colour = colour_string
                    user.profile.save()

    print(request.POST)
    image_url = user.profile.picture_url

    possible_images = []
    for x in range(number_of_custom_images):
        y = "img/profile_pictures/picture_" + str(x + 1) + ".png"
        y_url = static(y)
        possible_images.append(y_url)
    user_colour = user.profile.colour
    user_nickname = user.profile.nickname
    user_location = user.profile.location

    context = {
        "page_name": "Default",
        "wallets": wallets,
        "image_url": image_url,
        "possible_images": possible_images,
        "user_colour": user_colour,
        "user_nickname": user_nickname,
        "user_location": user_location
    }
    return render(request, "profiles/profileDetails.html", context)


# TODO: Make each group page glow with the colour of the group - In html most likely
@login_required(redirect_field_name="")
def profile_details_group(request, group_id):
    # Set user to request.user
    user = request.user

    group = get_object_or_404(CommunityGroup, id=group_id)

    # TODO: Replace these try statements with get-object-or-404's? Can the 404 message be stated this way?
    try:
        wallet = Wallet.objects.get(group=group, profile=user.profile, status=Wallet.active)
    except Wallet.DoesNotExist:
        raise Http404('You are not a member of this group.')

    if request.method == "POST":
        if 'form_name' in request.POST:
            form_name = request.POST['form_name']

            if form_name == "nickname":
                if "delete_nickname" in request.POST:
                    if request.POST['delete_nickname']:
                        # Set all other groups data to the default values
                        wallet.nickname = None
                        wallet.save()
                else:
                    form_dict = {
                        "nickname": request.POST['nickname']
                    }
                    form = NicknameForm(form_dict)
                    if form.is_valid():
                        nickname = form.cleaned_data['nickname']
                        wallet.nickname = nickname
                        wallet.save()
            elif form_name == "picture":
                form_dict = {
                    "picture_id": request.POST['picture_id']
                }
                form = ImageForm(form_dict)
                if form.is_valid():
                    picture_id = form.cleaned_data['picture_id']
                    wallet.picture_id = picture_id
                    wallet.save()
            elif form_name == "colour":
                form_dict = {
                    "colour_string": request.POST['colour_string']
                }
                form = ColourForm(form_dict)
                if form.is_valid():
                    colour_string = form.cleaned_data['colour_string']
                    colour_string = colour_string[1:]
                    wallet.colour = colour_string
                    wallet.save()
            # Re-fetch the wallet as changes may have been made
            wallet = Wallet.objects.get(group=group, profile=user.profile, status=Wallet.active)

    wallets = user.profile.profiles_wallet.all()

    image_url = wallet.picture_url

    possible_images = []
    for x in range(number_of_custom_images):
        y = "img/profile_pictures/picture_" + str(x + 1) + ".png"
        y_url = static(y)
        possible_images.append(y_url)
    user_colour = wallet.colour
    user_nickname = wallet.nickname
    user_location = user.profile.location

    context = {
        "page_name": group.name,
        "group_wallet": wallet,
        "wallets": wallets,
        "image_url": image_url,
        "possible_images": possible_images,
        "user_colour": user_colour,
        "user_nickname": user_nickname,
        "user_location": user_location
    }
    return render(request, "profiles/profileDetails.html", context)

Profiles/templates/profiles/profileDetails.html
{% extends "base.html" %}
{% load static %}

{# Set the url the forms on the page will post to #}
{% ifequal request.path default_profile_settings %}
    {% url 'profiles:profileDetailsDefault' as form_url %}
{% else %}
    {% url 'profiles:profileDetailsGroup' group_id=group_wallet.group.id as form_url %}
{% endifequal %}

{% block head_title %}Bets Admin | {{ block.super }}{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'groups/style.css' %}" />
    <meta charset="UTF-8">
{% endblock %}

{% block jumbotron %}


    {% include 'profiles/profileDetailsNav.html' %}

{% endblock %}


{% block content %}

<style>
{# Image selector css #}
.nopad {
	padding-left: 0 !important;
	padding-right: 0 !important;
}
/*image gallery*/
.image-checkbox {
	cursor: pointer;
	box-sizing: border-box;
	-moz-box-sizing: border-box;
	-webkit-box-sizing: border-box;
	border: 4px solid transparent;
	margin-bottom: 0;
	outline: 0;
}
.image-checkbox input[type="checkbox"] {
	display: none;
}

.image-checkbox-checked {
	border-color: #4783B0;
}
.image-checkbox .fa {
  position: absolute;
  color: #4A79A3;
  background-color: #fff;
  padding: 10px;
  top: 0;
  right: 0;
}
.image-checkbox-checked .fa {
  display: block !important;
}

{# Colour picker css #}
.pallette {
  height: 250px;
  width: 100%;
  background-color: red;
  background-image:
    linear-gradient(0deg, black, rgba(0,0,0,0)),
    linear-gradient(90deg, white, rgba(255,255,255,0))
    ;
  position: relative;
}

.pallette:hover {
  cursor: pointer;
}

.slider-bar {
  margin: 1em 0;
  height: 1em;
  border-radius: 0.3em;

  border: 1px solid #ccc;
  position: relative;
}

input[type="range"] {
  margin: 1em 0;
  width: 100%;
  -webkit-appearance: none;
  outline: none;
  background-image: linear-gradient(to right, red, yellow, hsl(120, 100%, 50%), cyan, blue, magenta, red);
  background-color: #fff;
  height: 2em;
  border-radius: .5em;
  box-sizing: border-box;
}

input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 2em;
  height: 2em;
  background: #333;
  cursor: pointer;
  border-radius: .3em;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

.result {
  text-align: center;
  font-size: 2em;
  padding: 2em 0;
  background-color: hsl(0, 100%, 50%);
  color: hsl(180, 100%, 50%);
}

.circle {
  position: absolute;
  top: 0;
  right: 0;
  width: 1em;
  height: 1em;
  background-color: transparent;
  border: 2px solid hsl(180, 100%, 50%);
  border-radius: 50%;
  transform: translate(-50%, -50%);
}
.square {
    width: 1rem;
    height: 1rem;
    background-color: #{{ user_colour }};
    display: inline-block;
    border: 1px black solid;
}
.form-box {
    padding: 1rem;
    border-radius: .5rem;
    background-color: rgba(0, 0, 0, 0.1);
    border: 1px solid rgb(86, 180, 239);
    box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.05) inset, 0px 0px 30px rgba(82, 168, 236, 0.6);
}
div:target {
  border: 1px solid rgb(86, 180, 239);
  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.05) inset, 0px 0px 30px rgba(82, 168, 236, 0.6);
}
</style>

<div class="betting-title rounded row" style=" margin-right: 0; margin-left: 0;">
    <div class="col-sm-8">
        <h4 class="display-4" style="font-size: 2.3rem;font-weight: 500; margin-bottom: .25rem;">{{ page_name }} Details </h4>
    </div>
    {% ifequal page_name "Default" %}
        <div class="col-sm-4" style="padding-top: 0.3rem;">
            <form method='POST' action='{{ form_url }}'>{% csrf_token %}
                <input type="hidden" name="form_name" value="set_default">
                <button class="btn btn-primary btn-block">
                  Set all groups to default values
                </button>
            </form>
        </div>
    {% endifequal %}
</div>
<div class="row">
    <div class="col-md-4 offset-md-2">
        <p><h5>Current Display Picture:</h5></p>
        <img style="height: 80%;" src="{{ image_url }}"/></br>
        <a href="#change_image">&lt;&lt;edit&gt;&gt;</a>
    </div>
    <div class="col-md-4">
        <p><h5>Current nickname:</h5> {{ user_nickname }} <a class="toggle_area" id="change_nickname" href="#">&lt;&lt;edit&gt;&gt;</a></p>
        <div class="form-box" id="change_nickname_form" style="display: none;">
            <form method='POST' action='{{ form_url }}'>{% csrf_token %}
                <input type="hidden" name="form_name" value="nickname">
                <input type="text" name="nickname" class="form-control" id="NicknameInput" placeholder="Enter Nickname Here" style="display: inline-block;">
                <div class="form-check form-check-inline">
                  <input class="form-check-input" name="delete_nickname" type="checkbox" id="delete_nickname" value="True">
                  <label class="form-check-label" for="delete_nickname">Remove Nickname</label>
                </div>
                <br>
                <br>
                <button class="btn btn-primary" style="display: block; width: 100%;">Save</button>
            </form>
        </div>
        <p><h5>Current location:</h5>
        {% ifequal page_name "Default" %}
            {{ user_location }}
            <a class="toggle_area" href="#">&lt;&lt;edit&gt;&gt;</a></p>
            <div class="form-box" id="change_location_form" style="display: none;">
                <form method='POST' action='{{ form_url }}'>{% csrf_token %}
                    <input type="hidden" name="form_name" value="location">
                    <input type="text" name="location" class="form-control" id="LocationInput" placeholder="Enter Location Here" style="display: inline-block;">
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" name="delete_location" type="checkbox" id="delete_location" value="True">
                      <label class="form-check-label" for="delete_location">Remove Location</label>
                    </div>
                    <br>
                    <br>
                    <button class="btn btn-primary" style="display: block; width: 100%;">Save</button>
                </form>
            </div>
        {% else %}
            <span data-toggle="tooltip" data-placement="right" title="Location can not be set on a group level.">
                {{ user_location }} <span style="font-weight: 720;">*</span>
            </span>
        {% endifequal %}
        <p><h5>Current colour:</h5><div class="square"></div> #{{ user_colour }} <a href="#change_colour">&lt;&lt;edit&gt;&gt;</a></p>
    </div>
</div>
<br>

<div class="row">
    <div class="col-sm-8">
        <form method='POST' action='{{ form_url }}'>{% csrf_token %}
            <input type="hidden" name="form_name" value="picture">
            <div class="card" id="change_image" style="border: 1px solid #b5b5b5; margin-bottom: 1rem;">
                <h5 class="card-header" style="background-color: rgba(0, 0, 0, 0.02);"> Change Default Picture</h5>
                <div class="card-body row" style="max-height: 500px; overflow: overlay; margin-left: 0; margin-right: 0;">

                   {% for image in possible_images %}
                      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 nopad text-center">
                        <div class="image-checkbox">
                          <img class="img-responsive" style="max-width: 100%;" src={{ image }} />
                          <input type="checkbox" name="picture_id" value="{{ forloop.counter }}" />
                          <i class="fa fa-check hidden" style="display: none; border: 1px black solid;"></i>
                        </div>
                      </div>
                    {% endfor %}

                </div>
                <div class="card-footer" style="padding: 0; background-color: rgba(0, 0, 0, 0.02);">
                  <button class="btn btn-primary btn-lg btn-block card-footer-btn">
                      Save
                  </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-sm-4">
        <form method='POST' action='{{ form_url }}'>{% csrf_token %}
            <input type="hidden" name="form_name" value="colour">
            <div class="card" id="change_colour" style="border: 1px solid #b5b5b5; margin-bottom: 1rem;">
                <h5 class="card-header" style="background-color: rgba(0, 0, 0, 0.02);"> Change Default Colour</h5>
                <div class="card-body" style="height: 500px;">
                    <div class="color-picker">
                        <div class="pallette">
                            <i class="circle"></i>
                        </div>

                            <div>
                              <input name="colour_range" type="range" min="0" max="360" value="0">
                              <input type="hidden" id="colour_string" name="colour_string" value="#FF0000">
                            </div>
                            <div class="result">
                              hsl(0, 100%, 50%)
                            </div>

                    </div>
                </div>
                <div class="card-footer" style="padding: 0; background-color: rgba(0, 0, 0, 0.02);">
                  <button class="btn btn-primary btn-lg btn-block card-footer-btn">
                      Save
                  </button>
                </div>
            </div>
        </form>
    </div>

</div>

<script>
// Change Nickname and location link
$(".toggle_area").click(function(){
    var current_box = $(this).next().next()
    $(".form-box").not(current_box).hide("slow");
    current_box.toggle("slow");
  });

// image gallery
// init the state from the input
$(".image-checkbox").each(function () {
  if ($(this).find('input[type="checkbox"]').first().attr("checked")) {
    $(this).addClass('image-checkbox-checked');
  }
  else {
    $(this).removeClass('image-checkbox-checked');
  }
});

// sync the state to the input
$(".image-checkbox").on("click", function (e) {
    $('.image-checkbox').removeClass('image-checkbox-checked');
    $(':checkbox').prop('checked', false);
    $(this).toggleClass('image-checkbox-checked');
    var $checkbox = $(this).find('input[type="checkbox"]');
    $checkbox.prop("checked", !$checkbox.prop("checked"))

    e.preventDefault();
});
// HSL to RGB converter
function hslToHex(h, s, l) {
  h /= 360;
  s /= 100;
  l /= 100;
  let r, g, b;
  if (s === 0) {
    r = g = b = l; // achromatic
  } else {
    const hue2rgb = (p, q, t) => {
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    r = hue2rgb(p, q, h + 1 / 3);
    g = hue2rgb(p, q, h);
    b = hue2rgb(p, q, h - 1 / 3);
  }
  const toHex = x => {
    const hex = Math.round(x * 255).toString(16);
    return hex.length === 1 ? '0' + hex : hex;
  };
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}
// Colour Picker
document.addEventListener("DOMContentLoaded", function() {
  let slider = document.querySelector("input[type='range']");
  let pallette = document.querySelector(".pallette");
  let result = document.querySelector(".result");
  let circle = document.querySelector(".circle");
  let colour_string = document.querySelector("#colour_string");
  let theColor = {h:0, s: 100, l: 50};

  function getColors() {
    return {
      color: `hsl(${theColor.h}, ${theColor.s}%, ${theColor.l}%)`,
      contrastColor: `hsl(${theColor.h - 180}, 100%, ${100 -theColor.l}%)`
    }
  }

  slider.addEventListener("input",function() {
    let paletteColor = `hsl(${this.value}, 100%, 50%)`;
    pallette.style.backgroundColor = paletteColor;

    theColor.h = this.value;

    colour_string.value = hslToHex(theColor.h, theColor.s, theColor.l);

    let {color, contrastColor} = getColors();
    result.innerHTML = color;
    result.style.backgroundColor = color;
    result.style.color = contrastColor;
    circle.style.borderColor = contrastColor;
  });

  pallette.addEventListener("click", function(ev) {
    let saturation = Math.round(100 * (ev.offsetX / this.clientWidth));
    // weird experimental math going on here
    let lightness = Math.round((50 * (1- (ev.offsetY / this.clientHeight))) * (2 - (saturation/100)));

    circle.style.top = ev.offsetY + "px";
    circle.style.left = ev.offsetX + "px";

    theColor = {h: slider.value, s: saturation, l: lightness};

    colour_string.value = hslToHex(theColor.h, theColor.s, theColor.l);

    let {color, contrastColor} = getColors();
    result.innerHTML = color;
    result.style.backgroundColor = color;
    result.style.color = contrastColor;
    circle.style.borderColor = contrastColor;
  });
});
{# Enable tooltips #}
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

Profiles/templates/profiles/profileDetailsNav.html
{% load static %}
{% url 'profiles:profileDetailsDefault' as default_profile_settings %}

<style>
    .nav-link.active_community {
        background-color: #e9ecef !important;
        border-color: #dee2e6 #b5b5b5 #e9ecef !important;
        color:black;
    }
</style>
<ul class="nav nav-tabs" style="padding-left: 10%; padding-right: 10%; background-color: #f6f6f6; border-bottom: 1px #b5b5b5 solid;">
  <li class="nav-item" style="margin-left: 0rem;">
    <a
            class="nav-link{% ifequal request.path default_profile_settings %} active_community{% endifequal %}"
            href="{{ default_profile_settings }}">
        <i class="fas fa-user-tie"></i> &nbsp Default Profile Settings
    </a>
  </li>
  {% for g in wallets %}
      {% url 'profiles:profileDetailsGroup' group_id=g.group.id as group_page %}
      <li class="nav-item" style="margin-left: 0rem;">
        <a
                class="nav-link{% ifequal request.path group_page %} active_community{% endifequal %}"
                href="{{ group_page }}">{{ g.group.name }}
        </a>
      </li>
  {% endfor %}
</ul>