CommunityTournaments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('Groups.urls'), name="groups"),
    path('', include('Profiles.urls'), name="profiles"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Groups/urls.py
from django.urls import path
from Groups import views


app_name = 'groups'
urlpatterns = [
    # ex: /betting/
    path('', views.groupsHome, name='home'),
    path('search/', views.groupSearch, name='groupSearch'),
    path('create/', views.createGroup, name='createGroup'),
    path('<int:group_id>/', views.group_page, name='groupPage'),
    path('<int:group_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts'),
    path('<int:group_id>/tournaments/<int:tournament_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts_tournament'),
    path('<int:group_id>/invite/<int:page>/', views.invitePage, name='invitePage'),
    path('<int:group_id>/admin/', views.adminPageOptions, name='adminPage'),
    path('<int:group_id>/admin/games/add/', views.adminPageAddGames, name='adminPageAddGames'),
    path('<int:group_id>/admin/tournaments/add/', views.adminPageAddTournament, name='adminPageAddTournament'),
    path('<int:group_id>/members/<int:page>/', views.groupMembers, name='groupMembers'),
    path('<int:group_id>/tournaments/', views.tournament_list_view, name='tournament_list_view'),
    path('<int:group_id>/tournaments/<int:tournament_id>/', views.tournament_view, name='tournament_view'),
    path('<int:group_id>/<int:betting_group_id>/', views.match_view, name='matchView'),
    path('<int:group_id>/completed-games/', views.completed_game_list_view, name='completed_games_list_view'),

]

Games/models.py
from django.db import models
from django.core.exceptions import ValidationError
from Profiles.models import Profile, Team, Wallet
from Groups.models import CommunityGroup
from datetime import timedelta
from django.templatetags.static import static

# Create your models here.


class Videogame(models.Model):
    name = models.CharField(unique=True, max_length=30, default="LoL")
    api_videogame_id = models.IntegerField(unique=True, null=True, blank=True)
    picture_id = models.IntegerField(default=1, null=False, blank=False)
    colour = models.CharField(max_length=7, null=False, blank=False, default="D3D3D3")
    alt_colour = models.CharField(max_length=7, null=False, blank=False, default="D3D3D3")

    @property
    def picture_url(self):
        image = "img/game_logos/logo_" + str(self.picture_id) + ".png"
        return static(image)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    name = models.CharField(max_length=120, null=False, blank=False)
    api_tournament_id = models.IntegerField(unique=True, null=True, blank=True)
    api_modified_at = models.DateTimeField('api_modified_at',null=True, blank=True)

    owning_group = models.ForeignKey(
        CommunityGroup,
        related_name='owning_group_tournaments',
        default=1,
        blank=False,
        null=False,
        on_delete=models.PROTECT
    )

    videogame = models.ForeignKey(
        Videogame,
        related_name='videogame_tournaments',
        blank=True,
        null=True,
        on_delete=models.PROTECT
    )
    start_datetime = models.DateTimeField('Tournament start date')
    end_datetime = models.DateTimeField('Tournament end date', blank=True, null=True)

    twitch_url = models.URLField(max_length=200, unique=False, blank=True, null=True)

    not_begun = "Not begun"
    ongoing = "Ongoing"
    finished = "Finished"


    available_statuses = ((not_begun, "Not begun"),
                           (ongoing, "Ongoing"),
                           (finished, "Finished"))

    status = models.CharField(max_length=30,
                              choices=available_statuses,
                              default=not_begun)

    def __str__(self):
        return self.name


class Match(models.Model):
    api_match_id = models.IntegerField(unique=True,blank=True,null=True)
    api_modified_at = models.DateTimeField('api_modified_at',null=True, blank=True)

    team_a = models.ForeignKey(Team, on_delete=models.PROTECT, related_name='%(class)s_team_a', blank=True,null=True)
    team_b = models.ForeignKey(Team, on_delete=models.PROTECT, related_name='%(class)s_team_b', blank=True,null=True)

    user_a = models.ForeignKey(Wallet, on_delete=models.PROTECT, related_name='%(class)s_user_a', blank=True,null=True)
    user_b = models.ForeignKey(Wallet, on_delete=models.PROTECT, related_name='%(class)s_user_b', blank=True,null=True)

    tournament = models.ForeignKey(Tournament, related_name='tournament_matches', blank=False, null=False, on_delete=models.PROTECT)
    start_datetime = models.DateTimeField('Game start datetime')
    estimated_duration = models.DurationField(default=timedelta(minutes=2))

    twitch_url = models.URLField(max_length=200, unique=False, blank=True, null=True)

    a_winner = "A is the winner"
    b_winner = "B is the winner"
    not_decided = "Not Decided"
    teams = ((not_decided, "Not Decided"),
             (a_winner, "A is the winner"),
             (b_winner, "B is the winner"))

    winner = models.CharField(
        max_length=60,
        choices=teams,
        default= not_decided,
        unique=False,
        blank=False,
        null=False
    )

    not_started = "not_started"
    starting = "Starting"
    running = "running"
    finished = "finished"
    finished_not_confirmed = "Finished - Not yet confirmed"
    finished_confirmed = "Finished - Confirmed"
    finished_paid = "Finished - All bets paid"

    available_statuses = ((not_started, "Not started"),
                           (starting, "Starting"),
                           (running, "Running"),
                           (finished, "Finished"),
                           (finished_not_confirmed, "Finished - Not yet confirmed"),
                           (finished_confirmed, "Finished - Confirmed"),
                           (finished_paid, "Finished - All bets paid"))

    status = models.CharField(max_length=30,
                              choices=available_statuses,
                              default=not_started)

    # Goal: Make it so that teamaa =/ team_b...
    # Useful thread = https://stackoverflow.com/questions/35096607/how-to-enforce-different-values-in-multiple-foreignkey-fields-for-django

    def clean(self):  # Used to raise validation errors if a mix of users and teams are assigned to a game
        super(Match, self).clean()
        # raise error if none are filled out or both are filled out + if a team is against a user
        if self.user_a is not None and self.team_a is not None:
            raise ValidationError('Only user_a or team_a can be filled out')
        elif self.user_b is not None and self.team_b is not None:
            raise ValidationError('Only user_b or team_b can filled out')
        elif self.user_a is None and self.team_a is None:
            raise ValidationError('Either user_a or team_a must filled out')
        elif self.user_b is None and self.team_b is None:
            raise ValidationError('Either user_b or team_b must filled out')
        elif self.user_a is not None and self.team_b is not None:
            raise ValidationError('A user cannot play versus a team')
        elif self.user_b is not None and self.team_a is not None:
            raise ValidationError('A user cannot play versus a team')

    def save(self, *args, **kwargs):  # Exceptions raised if values for teams or values for users ar the same
        try:
            if self.team_a == self.team_b:
                raise Exception('attempted to create a match object where team_a == team_b')
        except:
            pass
        try:
            if self.user_a == self.user_b:
                raise Exception('attempted to create a match object where user_a == user_b')
        except:
            pass
        super(Match, self).save(*args, **kwargs)

    def __str__(self):
        if self.team_a is not None:
            return str(self.team_a) + " vs " + str(self.team_b) + " - " + str(self.start_datetime)
        else:
            return str(self.user_a) + " vs " + str(self.user_b) + " - " + str(self.start_datetime)

Groups/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class CommunityGroup(models.Model):
    name = models.CharField(max_length=200, null=False, unique=True)
    private = models.BooleanField(default=False)
    daily_payout = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    removable = models.BooleanField(default=True)
    max_users = models.IntegerField(default=32, blank=False, null=False)
    total_users = models.IntegerField(default=0, editable=False)
    members_can_inv = models.BooleanField(default=True)
    header_background_colour = models.CharField(max_length=7, null=False, blank=False, default="ffffff")
    header_text_colour = models.CharField(max_length=7, null=False, blank=False, default="000000")

    active = "active"
    deactivated = "deactivated"

    available_statuses = ((active, "Active"),
                           (deactivated, "Deactivated"))

    status = models.CharField(max_length=30,
                              choices=available_statuses,
                              default=active,
                              null=False,
                              blank=False)

    def __str__(self):
        return self.name

Groups/forms.py
from django import forms
from decimal import Decimal
from .models import CommunityGroup

class CreateGroupForm(forms.Form):
    group_name = forms.CharField(max_length=120)
    invite_only = forms.BooleanField(required=False)
    members_can_invite = forms.BooleanField(required=False)
    header_background_colour = forms.CharField(max_length=7)
    header_text_colour = forms.CharField(max_length=7)
    tournaments = forms.CharField(required=False)
    daily_payout = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'), required=False)

    def clean(self):
        cd = self.cleaned_data
        name = cd.get('group_name').lower()
        if "public" in name:
            self.add_error('group_name', "You cannot have the word 'public' in your community's name !")
        for t in CommunityGroup.objects.all():
            if name == t.name.lower():
                self.add_error('group_name', "The community name must be unique !")
        return cd

class UpdateGroupOptionsForm(forms.Form):
    invite_only = forms.BooleanField(required=False)
    members_can_invite = forms.BooleanField(required=False)
    header_background_colour = forms.CharField(max_length=7)
    header_text_colour = forms.CharField(max_length=7)
    daily_payout = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'), required=False)

class InviteMembersForm(forms.Form):
    profile_id = forms.IntegerField(required=True)

class MembersAdminCommandForm(forms.Form):
    wallet_id = forms.IntegerField(required=True)
    admin_command = forms.CharField(required=True, max_length=16)


class AcceptInviteForm(forms.Form):
    accept_invite = forms.BooleanField(required=False)
    wallet_id = forms.IntegerField(required=True)

class JoinGroupForm(forms.Form):
    group_id = forms.IntegerField(required=True)

class CreateTournamentForm(forms.Form):
    tournament_name = forms.CharField(max_length=120)
    videogame_id = forms.IntegerField()
    tournament_start_date = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    tournament_end_date = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    twitch_url = forms.URLField()
    def clean(self):
        cd = self.cleaned_data
        start_date = cd.get('tournament_start_date')
        end_date = cd.get('tournament_end_date')

        if end_date < start_date:
            self.add_error('tournament_end_date', "Your tournament end date is earlier than your tournament start date")

        return cd


class UpdateTournamentDateForm(forms.Form):
    tournament_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    tournament_end_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    def clean(self):
        cd = self.cleaned_data
        start_date = cd.get('tournament_start_datetime')
        end_date = cd.get('tournament_end_datetime')

        if end_date < start_date:
            self.add_error('tournament_end_datetime', "Your tournament end date is earlier than your tournament start date")

        return cd

class UpdateStatusForm(forms.Form):
    status = forms.CharField(max_length=40)


class UpdateUrlForm(forms.Form):
    url = forms.URLField()

class UpdateVideogameForm(forms.Form):
    videogame_id = forms.IntegerField()

class UpdateWinnerForm(forms.Form):
    winner = forms.IntegerField()

class CreateGameForm(forms.Form):
    tournament_id = forms.IntegerField()
    user_a = forms.IntegerField()
    user_b = forms.IntegerField()
    game_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    game_duration = forms.IntegerField()
    twitch_url = forms.URLField()

    def clean(self):
        cd = self.cleaned_data
        user_a = cd.get('user_a')
        user_b = cd.get('user_b')

        if user_a == user_b:
            self.add_error('user_b', "A user cannot play against themselves.")

        return cd


class UpdateMatchDateForm(forms.Form):
    match_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    match_duration = forms.IntegerField()


class BetForm(forms.Form):
    chosen_team = forms.CharField(max_length=200)
    amount = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'))


class ChatForm(forms.Form):
    chat_message = forms.CharField(max_length=1024)

Games/views.py
from django.shortcuts import render

# Create your views here.

Groups/templates/groups/completed_game_list_view.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Completed Games | {{ block.super }}{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'groups/style.css' %}" />
    <meta charset="UTF-8">
{% endblock %}

{% block jumbotron %}
{% include 'groups/group_jumbotron.html' with title_pager="Completed Games" %}

    {% include 'groups/group_nav.html' %}

{% endblock %}

{% block content %}

  {% if latest_game_list %}
        <div id="games_list" class="row grid-view">
            {% include 'groups/games_list.html' %}
        </div>
  {% else %}
        <p>No completed games are available at this time.</p>
  {% endif %}
{##}
{#<div class="list-group">#}
{#{% for profile in model %}#}
{#    <a href="{% url 'profiles:profile-public' profile.username %}" class="list-group-item list-group-item-action">#}
{#        {{ profile.username }}#}
{#    </a>#}
{#{% endfor %}#}
{#</div>#}

{% endblock %}

Groups/templates/groups/group_jumbotron.html
<div class="jumbotron" style="padding-left: 10%; padding-right: 10%; position: relative; background-color: #{{ group.header_background_colour }}; padding-bottom: 25px; padding-top: 20px; border-bottom: 1px #b5b5b5 solid; border-radius: 0;">
    <div class="container home-wide">
        <div class="row" style="border-bottom: 2px solid #{{ group.header_text_colour }}; margin-bottom: 15px;">
            <div class="col-md-12">
                <p class='display-3 text-align-left' style="margin-bottom: 0; color: #{{ group.header_text_colour }}">{{ group.name }} {{ title_pager }}</p>
            </div>
        </div>
    </div>
{#    {% ifnotequal group.name 'PUBLIC' %}#}
{#        <div style="position: absolute; width: 0;height: 0;border-bottom: 32px solid #343a40;border-left: 20px solid transparent;right:80px; bottom: 0px;">#}
{#        </div>#}
{#        <div style="position: absolute; width: 0;height: 0;border-bottom: 30px solid #ffffff;border-left: 19px solid transparent;right:80px; bottom: 0px;">#}
{#        </div>#}
{#        <div style="position: absolute; width: 0;height: 0;border-bottom: 27px solid #f6f6f6;border-left: 17px solid transparent;right:80px; bottom: 0px;">#}
{#        </div>#}
{##}
{#        <div style="position: absolute; height: 30px;width: 80px;right:0px; bottom: 1px; background-color: #343a40;">#}
{#            <div style="margin-top: 1px; border-top: 2px #ffffff solid; height: 100%; background-color: #f6f6f6;">#}
{#                <p style="margin-bottom: 0; padding: 0.25rem; font-weight: 600;">User Group</p>#}
{#            </div>#}
{#        </div>#}
{#    {% endifnotequal %}#}
</div>

Groups/templates/groups/group_nav.html
{% load static %}
{% url 'groups:groupPage' group_id=group.id as group_page %}
{% url 'groups:tournament_list_view' group_id=group.id as tournament_page %}
{% url 'groups:adminPage' group_id=group.id as admin_page %}
{% url 'groups:invitePage' group_id=group.id page=1 as invite_page %}
{% url 'groups:groupMembers' group_id=group.id page=1 as member_page %}
{% url 'groups:completed_games_list_view' group_id=group.id as completed_games %}

<style>
    .nav-link.active_community {
        background-color: #e9ecef !important;
        border-color: #dee2e6 #b5b5b5 #e9ecef !important;
        color:black;
    }
</style>
<ul class="nav nav-tabs" style="padding-left: 10%; padding-right: 10%; background-color: #f6f6f6; border-bottom: 1px #b5b5b5 solid;">
  <li class="nav-item" style="margin-left: 0rem;">
    <a
            class="nav-link{% ifequal request.path group_page %} active_community{% endifequal %}"
            href="{{ group_page }}">
        <i class="fas fa-home"></i> &nbsp{{ group.name }} Home
    </a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% ifequal request.path tournament_page %} active_community{% endifequal %}" data-toggle="dropdown" href="{{ tournament_page }}" role="button" aria-haspopup="true" aria-expanded="false">Tournaments</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{{ tournament_page }}?activesection=upcoming">Upcoming</a>
      <a class="dropdown-item" href="{{ tournament_page }}?activesection=ongoing">Ongoing</a>
      <a class="dropdown-item" href="{{ tournament_page }}?activesection=completed">Completed</a>
{#      <div class="dropdown-divider"></div>#}
{#      <a class="dropdown-item" href="#">Separated link</a>#}
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link{% ifequal  request.get_full_path invite_page %} active_community{% endifequal %}" href="{{ invite_page }}">Invite</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% ifequal  request.get_full_path member_page %} active_community{% endifequal %}" href="{{ member_page }}">Members</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if admin_page in request.path %} active_community{% endif %}" href="{{ admin_page }}">Admin</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% ifequal  request.path completed_games %} active_community{% endifequal %}" href="{{ completed_games }}">Completed Games</a>
  </li>
{#  <li class="nav-item">#}
{#    <a class="nav-link disabled" href="#">Admin</a>#}
{#  </li>#}
</ul>

Groups/templates/groups/home.html
{% extends "base.html" %}
{% load static %}


{% block head_title %}Bets Admin | {{ block.super }}{% endblock %}

{% block extracss %}
    <style>
        main {
        background-color: #e9ecef;
    }
    .home-wide {
        padding-top: 2rem !important;
    }
    body { height:100vh; }
    </style>
{% endblock %}

{% block jumbotron %}

{% endblock %}


{% block content %}
<div class="row" style="margin-bottom: 1.5rem;">
    <div class="col-md-4" id="SearchAndCreate">
        <a class='btn btn-primary' href="{% url 'groups:groupSearch' %}" style="height: 12rem;width: 100%; margin-bottom: 5px;"><p style="font-size: 3rem;white-space: normal;margin-bottom: 0;">Search for Groups<p></p></a>
        <a class='btn btn-info' href="{% url 'groups:createGroup' %}" style="height: 4rem; width: 100%; font-size: 200%; line-height: 3rem; text-align:center;">Create Group</a>
    </div>
    <div class="col-md-8" id="CurrentGroups">
         <div class="card" style="border: 1px solid #b5b5b5;height: 100%;">
              <h5 class="card-header" style="background-color: rgba(0, 0, 0, 0.02);"> <span data-toggle="tooltip" data-placement="right" title="Only 4 nearest tournaments displayed">Current Groups</span></h5>
              <div class="card-body" style="padding: 0;">
                <table class="table table-striped header-fixed" style="margin-bottom: 0;">
                      <thead>
                        <tr style="border-bottom: 2px solid #dee2e6;">
                          <th scope="col" style="width: 52%; border-bottom: 0;">Group Name</th>
                          <th scope="col" style="width: 16%; border-bottom: 0;">Ranking</th>
                          <th scope="col" style="width: 16%; border-bottom: 0;">Current Bank</th>
                          <th scope="col" style="width: 16%; border-bottom: 0;">Outstanding</th>
                        </tr>
                      </thead>
                      <tbody style="height: auto; overflow: auto; max-height: 180px;">
                      {% for item in wallets %}
                        <tr style="background-color: {% ifequal bet.status bet.paid %}rgba(0,255,0,0.1){% else %}rgba(255,0,0,0.1) {% endifequal %}">
                            <td style="width: 52%;"><a href="{% url "groups:groupPage" item.group.id %}">{{ item.group.name }}</a></td>
                          <td style="width: 16%;">{{ item.ranking }}</td>
                          <td style="width: 16%;">{{ item.bank }}</td>
                          <td style="width: 16%;">5</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                </table>
              </div>
{#            <div class="card-footer" style="padding: 0; background-color: rgba(0, 0, 0, 0.02);">#}
{#              yes#}
{#            </div>#}
        </div>


    </div>
</div>

<div class="row">
    <div class="col-md-8" id="Invites">
        <div class="card" style="border: 1px solid #b5b5b5;height: 100%;">
              <h5 class="card-header" style="background-color: rgba(0, 0, 0, 0.02);"> <span data-toggle="tooltip" data-placement="right" title="Only 4 nearest tournaments displayed">Group Invites</span></h5>
              <div class="card-body" style="padding: 0;">
                <table class="table table-striped header-fixed" style="margin-bottom: 0;">
                  <thead>
                   <tr style="border-bottom: 2px solid #dee2e6;">
                      <th scope="col" style="width: 54%; border-bottom: 0;">Group Name</th>
                      <th scope="col" style="width: 30%; border-bottom: 0;">Inviter Name</th>
                      <th scope="col" style="width: 16%; border-bottom: 0;"></th>
                    </tr>
                  </thead>
                  <tbody style="height: auto; overflow: auto; max-height: 180px;">
                    {% for item in invites %}
                         <tr style="background-color: {% ifequal bet.status bet.paid %}rgba(0,255,0,0.1){% else %}rgba(255,0,0,0.1) {% endifequal %}">
                          <td style="width: 54%;"><a href="{% url "groups:groupPage" item.group.id %}">{{ item.group.name }}</a></td>
                          <td style="width: 30%;">{{ item.inviter }}</td>
                          <td style="width: 16%;">
                              <div style="float: right;">
                                  <form action="{% url 'groups:home' %}" method="post">{% csrf_token %}
                                      <input type="hidden" value={{ item.id }} name="wallet_id">

                                      <button
                                              class="btn"
                                              name="accept_invite"
                                              value=True
                                              style="
                                                font-size: 82%;
                                                background-color: #4CAF50;
                                                color: white;
                                                font-weight: 500;
                                                padding: initial;
                                                width: 25px;
                                                height: 25px;"
                                              type="submit"
                                      >
                                        <i class="fas fa-check"></i>
                                      </button>
                                      <button
                                              class="btn"
                                              name="accept_invite"
                                              value=False
                                              style="
                                                font-size: 82%;
                                                background-color: #f44336;
                                                color: white;
                                                font-weight: 500;
                                                padding: initial;
                                                width: 25px;
                                                height: 25px;"
                                              type="submit"

                                      >
                                        <i class="fas fa-times"></i>
                                      </button>
                                  </form>
                              </div>
                          </td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
{#                <div class="card-footer" style="padding: 0; background-color: rgba(0, 0, 0, 0.02);">#}
{#                  yes#}
{#                </div>#}
        </div>
    </div>
    <div class="col-md-4" id="AdminGroups">
        <div class="card" style="border: 1px solid #b5b5b5;height: 100%;">
              <h5 class="card-header" style="background-color: rgba(0, 0, 0, 0.02);"> <span data-toggle="tooltip" data-placement="right" title="Only 4 nearest tournaments displayed">Admin Access</span></h5>
              <div class="card-body" style="padding: 0;">
                <table class="table table-striped header-fixed" style="margin-bottom: 0;">
                  <thead>
                    <tr style="border-bottom: 2px solid #dee2e6;">
                      <th scope="col" style="width: 100%; border-bottom: 0;">Group Name</th>
                    </tr>
                  </thead>
                  <tbody style="height: auto; overflow: auto; max-height: 180px;">
                  {% for item in admin_wallets %}
                    <tr style="background-color: {% ifequal bet.status bet.paid %}rgba(0,255,0,0.1){% else %}rgba(255,0,0,0.1) {% endifequal %}">
                        <td style="width: 52%;"><a href="{% url "groups:groupPage" item.group.id %}">{{ item.group.name }}</a></td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
{#                <div class="card-footer" style="padding: 0; background-color: rgba(0, 0, 0, 0.02);">#}
{#                  yes#}
{#                </div>#}
        </div>
    </div>
</div>

<div style="position: absolute; bottom: 0.25rem; right: 0.25rem;">
 <a href="#" onclick="help()">Need help?</a>
</div>

<script>
function help() {
    $("body").append('<div id = "greydiv" style="height: 100vh;\n' +
        '    width: 100vw;\n' +
        '    display: block;\n' +
        '    background-color: rgba(0,0,0,0.5);\n' +
        '    z-index: 0;\n' +
        '    top: 0;\n' +
        '    position: absolute;"' +
        'data-helppage=1>' +
        '</div>' +
        '<div id="helpButtons" style="' +
        '    display: block;\n' +
        '    z-index: 1;\n' +
        '    bottom: 2rem;\n' +
        '    left: 45vw;\n' +
        '    position: absolute;">' +
        '<ul class="pagination">\n' +
        '    <li class="page-item" onclick="previousHelp()">\n' +
        '      <span class="page-link">Previous</span>\n' +
        '    </li>\n' +
        '    <li class="page-item" onclick="nextHelp()">\n' +
        '      <span class="page-link">Next</span>\n' +
        '    </li>\n' +
        '</ul>' +
        '</div>'
    );
    displayHelp();
};
function displayHelp() {
    {# Fetch page number and increase by 1#}
    var greydiv = $("#greydiv");
    var helpPage = greydiv.data("helppage");

    var SearchAndCreate = $("#SearchAndCreate");
    var CurrentGroups = $("#CurrentGroups");
    var Invites = $("#Invites");
    var AdminGroups = $("#AdminGroups");

    {#Set z-index for all elements to 0 #}
    SearchAndCreate.css('z-index',0);
    CurrentGroups.css('z-index',0);
    Invites.css('z-index',0);
    AdminGroups.css('z-index',0);

    if(helpPage == 1) {
        SearchAndCreate.css('z-index',2);
        console.log(helpPage);
    }
    else if(helpPage == 2) {
        CurrentGroups.css('z-index',2);
        console.log(helpPage);
    }
    else if(helpPage == 3) {
        Invites.css('z-index',2);
        console.log(helpPage);
    }
    else if(helpPage == 4) {
        AdminGroups.css('z-index',2);
        console.log(helpPage);
    }
    else {
        var helpButtons = $("#helpButtons");
        greydiv.remove();
        helpButtons.remove();
    };
};

function nextHelp(){
    {# Fetch page number and increase by 1#}
    var greydiv = $("#greydiv");
    var helpPage = greydiv.data("helppage") + 1;

    greydiv.data("helppage", helpPage);

    displayHelp();
};

function previousHelp(){
    {# Fetch page number and increase by 1#}
    var greydiv = $("#greydiv");
    var helpPage = greydiv.data("helppage") - 1;

    greydiv.data("helppage", helpPage);

    displayHelp();
};

</script>

{% endblock %}