CommunityTournaments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('Groups.urls'), name="groups"),
    path('', include('Profiles.urls'), name="profiles"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Groups/urls.py
from django.urls import path
from Groups import views


app_name = 'groups'
urlpatterns = [
    # ex: /betting/
    path('', views.groupsHome, name='home'),
    path('search/', views.groupSearch, name='groupSearch'),
    path('create/', views.createGroup, name='createGroup'),
    path('<int:group_id>/', views.group_page, name='groupPage'),
    path('<int:group_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts'),
    path('<int:group_id>/tournaments/<int:tournament_id>/lazy_load_games/', views.lazy_load_games, name='lazy_load_posts_tournament'),
    path('<int:group_id>/invite/<int:page>/', views.invitePage, name='invitePage'),
    path('<int:group_id>/admin/', views.adminPageOptions, name='adminPage'),
    path('<int:group_id>/admin/games/add/', views.adminPageAddGames, name='adminPageAddGames'),
    path('<int:group_id>/admin/tournaments/add/', views.adminPageAddTournament, name='adminPageAddTournament'),
    path('<int:group_id>/members/<int:page>/', views.groupMembers, name='groupMembers'),
    path('<int:group_id>/tournaments/', views.tournament_list_view, name='tournament_list_view'),
    path('<int:group_id>/tournaments/<int:tournament_id>/', views.tournament_view, name='tournament_view'),
    path('<int:group_id>/<int:betting_group_id>/', views.match_view, name='matchView'),
    path('<int:group_id>/completed-games/', views.completed_game_list_view, name='completed_games_list_view'),

]

Groups/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class CommunityGroup(models.Model):
    name = models.CharField(max_length=200, null=False, unique=True)
    private = models.BooleanField(default=False)
    daily_payout = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    removable = models.BooleanField(default=True)
    max_users = models.IntegerField(default=32, blank=False, null=False)
    total_users = models.IntegerField(default=0, editable=False)
    members_can_inv = models.BooleanField(default=True)
    header_background_colour = models.CharField(max_length=7, null=False, blank=False, default="ffffff")
    header_text_colour = models.CharField(max_length=7, null=False, blank=False, default="000000")

    active = "active"
    deactivated = "deactivated"

    available_statuses = ((active, "Active"),
                           (deactivated, "Deactivated"))

    status = models.CharField(max_length=30,
                              choices=available_statuses,
                              default=active,
                              null=False,
                              blank=False)

    def __str__(self):
        return self.name

Groups/forms.py
from django import forms
from decimal import Decimal
from .models import CommunityGroup

class CreateGroupForm(forms.Form):
    group_name = forms.CharField(max_length=120)
    invite_only = forms.BooleanField(required=False)
    members_can_invite = forms.BooleanField(required=False)
    header_background_colour = forms.CharField(max_length=7)
    header_text_colour = forms.CharField(max_length=7)
    tournaments = forms.CharField(required=False)
    daily_payout = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'), required=False)

    def clean(self):
        cd = self.cleaned_data
        name = cd.get('group_name').lower()
        if "public" in name:
            self.add_error('group_name', "You cannot have the word 'public' in your community's name !")
        for t in CommunityGroup.objects.all():
            if name == t.name.lower():
                self.add_error('group_name', "The community name must be unique !")
        return cd

class UpdateGroupOptionsForm(forms.Form):
    invite_only = forms.BooleanField(required=False)
    members_can_invite = forms.BooleanField(required=False)
    header_background_colour = forms.CharField(max_length=7)
    header_text_colour = forms.CharField(max_length=7)
    daily_payout = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'), required=False)

class InviteMembersForm(forms.Form):
    profile_id = forms.IntegerField(required=True)

class MembersAdminCommandForm(forms.Form):
    wallet_id = forms.IntegerField(required=True)
    admin_command = forms.CharField(required=True, max_length=16)


class AcceptInviteForm(forms.Form):
    accept_invite = forms.BooleanField(required=False)
    wallet_id = forms.IntegerField(required=True)

class JoinGroupForm(forms.Form):
    group_id = forms.IntegerField(required=True)

class CreateTournamentForm(forms.Form):
    tournament_name = forms.CharField(max_length=120)
    videogame_id = forms.IntegerField()
    tournament_start_date = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    tournament_end_date = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    twitch_url = forms.URLField()
    def clean(self):
        cd = self.cleaned_data
        start_date = cd.get('tournament_start_date')
        end_date = cd.get('tournament_end_date')

        if end_date < start_date:
            self.add_error('tournament_end_date', "Your tournament end date is earlier than your tournament start date")

        return cd


class UpdateTournamentDateForm(forms.Form):
    tournament_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    tournament_end_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    def clean(self):
        cd = self.cleaned_data
        start_date = cd.get('tournament_start_datetime')
        end_date = cd.get('tournament_end_datetime')

        if end_date < start_date:
            self.add_error('tournament_end_datetime', "Your tournament end date is earlier than your tournament start date")

        return cd

class UpdateStatusForm(forms.Form):
    status = forms.CharField(max_length=40)


class UpdateUrlForm(forms.Form):
    url = forms.URLField()

class UpdateVideogameForm(forms.Form):
    videogame_id = forms.IntegerField()

class UpdateWinnerForm(forms.Form):
    winner = forms.IntegerField()

class CreateGameForm(forms.Form):
    tournament_id = forms.IntegerField()
    user_a = forms.IntegerField()
    user_b = forms.IntegerField()
    game_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    game_duration = forms.IntegerField()
    twitch_url = forms.URLField()

    def clean(self):
        cd = self.cleaned_data
        user_a = cd.get('user_a')
        user_b = cd.get('user_b')

        if user_a == user_b:
            self.add_error('user_b', "A user cannot play against themselves.")

        return cd


class UpdateMatchDateForm(forms.Form):
    match_start_datetime = forms.DateTimeField(input_formats=['%H:%M - %d/%m/%Y'])
    match_duration = forms.IntegerField()


class BetForm(forms.Form):
    chosen_team = forms.CharField(max_length=200)
    amount = forms.DecimalField(max_digits=7, decimal_places=2, min_value=Decimal('0.01'))


class ChatForm(forms.Form):
    chat_message = forms.CharField(max_length=1024)

Groups/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from Profiles.models import Wallet, Profile
from .forms import *
from django.shortcuts import redirect
from django.contrib import messages
from Games.models import Tournament, Match, Videogame
from Bets.models import MatchBettingGroup, Bet
from django.http import Http404
from django.utils import timezone
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.staticfiles.templatetags.staticfiles import static

User = get_user_model()
# Create your views here.
landing_page_url = reverse_lazy('profiles:landingPage')


@login_required(login_url=landing_page_url, redirect_field_name="")
def groupsHome(request):
    user = request.user

    wallets = user.profile.profiles_wallet.all()
    admin_wallets = wallets.filter(Q(admin=True))
    invites = wallets.filter(
        Q(status=Wallet.sent)
    )
    form = AcceptInviteForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            wallet_id = form.cleaned_data['wallet_id']
            accept_invite = form.cleaned_data['accept_invite']
            wallet = get_object_or_404(Wallet, id=wallet_id)

            # Ensure the wallet in question actually belongs to the requesting user
            if wallet.profile == user.profile:

                # Ensure that the wallet is an active invite
                if wallet.status == wallet.sent:

                    # Check that the post request is accepting or declining the invite,
                    # then change the status accordingly
                    if accept_invite:
                        wallet.status = wallet.active

                    else:
                        wallet.status = wallet.declined

                    wallet.save()
                else:
                    form.add_error(None, "This invite is not active.")

            else:
                form.add_error(None, "You are not the owner of this invite.")

    context = {
        "wallets": wallets,
        "admin_wallets": admin_wallets,
        "invites": invites,
        "form": form
    }
    return render(request, 'groups/home.html', context)


@login_required(redirect_field_name="")
def groupSearch(request):
    user = request.user

    user_groups = user.profile.groups.all()

    groups = CommunityGroup.objects.all().exclude(id__in=user_groups).order_by('private')
    wallets = user.profile.profiles_wallet.all().order_by('group__private')
    form = JoinGroupForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            group_id = form.cleaned_data['group_id']

            group = get_object_or_404(CommunityGroup, id=group_id)

            wallet, wallet_created = Wallet.objects.get_or_create(
                profile=user.profile,
                group=group,
                defaults={
                    "status": Wallet.deactivated
                }
            )

            if wallet_created:
                if group.private:
                    # ask for invite
                    wallet.status = wallet.requesting_invite
                    messages.success(request, 'Invite requested')
                else:
                    wallet.status = wallet.active
                    messages.success(request, 'Successfully joined group.')
            else:
                if wallet.status == wallet.active:
                    form.add_error(None, "You are already a member of this group.")
                elif wallet.status == wallet.blocked_by_group:
                    form.add_error(None, "This group has blocked you. Please contact the group admin.")
                else:
                    if group.private:
                        # ask for invite
                        if wallet.status == wallet.requesting_invite:
                            form.add_error(None, "You have already requested an invite from this group.")
                        else:
                            wallet.status = wallet.requesting_invite
                            messages.success(request, 'Invite requested')
                    else:
                        wallet.status = wallet.active
                        messages.success(request, 'Successfully joined group.')
            wallet.save()

    context = {
        "model": groups,
        "form": form,
        "wallets": wallets
    }
    return render(request, 'groups/group_search.html', context)


@login_required(redirect_field_name="")
def createGroup(request):
    form = CreateGroupForm()

    if request.method == "POST":
        group_name = request.POST['group_name']
        if 'invite_only' in request.POST:
            invite_only = request.POST['invite_only']
        else:
            invite_only = False
        if 'members_can_invite' in request.POST:
            members_can_invite = request.POST['members_can_invite']
        else:
            members_can_invite = False
        header_background_colour = request.POST['header_background_colour']
        header_text_colour = request.POST['header_text_colour']
        daily_payout = request.POST["daily_payout"]

        form_dict = {
            "group_name": group_name,
            "invite_only": invite_only,
            "members_can_invite": members_can_invite,
            "header_background_colour": header_background_colour,
            "header_text_colour": header_text_colour,
            "daily_payout": daily_payout
        }
        form = CreateGroupForm(form_dict)

        # check whether it's valid:
        if form.is_valid():
            user = get_object_or_404(User, username=request.user)
            group_name = form.cleaned_data['group_name']
            invite_only = form.cleaned_data['invite_only']
            members_can_invite = form.cleaned_data['members_can_invite']
            header_background_colour = form.cleaned_data['header_background_colour']
            header_text_colour = form.cleaned_data['header_text_colour']
            daily_payout = form.cleaned_data['daily_payout']

            new_group = CommunityGroup()
            new_group.name = group_name
            new_group.private = invite_only
            new_group.members_can_inv = members_can_invite
            new_group.header_background_colour = header_background_colour
            new_group.header_text_colour = header_text_colour
            new_group.daily_payout = daily_payout
            new_group.save()

            user_wallet = Wallet()
            user_wallet.profile = user.profile
            user_wallet.group = new_group
            user_wallet.withdrawable_bank = daily_payout
            user_wallet.founder = True
            user_wallet.admin = True
            user_wallet.save()

            return redirect('groups:groupPage', group_id=new_group.id)

    context = {
        "form": form
    }
    return render(request, 'groups/create_group.html', context)


@login_required(redirect_field_name="")
def group_page(request, group_id):
    # Set user to request.user
    user = request.user

    # Fetch the group object
    group = get_object_or_404(CommunityGroup, id=group_id)

    # Attempt to get the ACTIVE wallet for this user for this group
    # If this fails then the user is not a member of the group and should be presented with a 404
    try:
        wallet = Wallet.objects.get(group=group, profile=user.profile, status=Wallet.active)
    except Wallet.DoesNotExist:
        raise Http404('You are not a member of this group.')

    latest_game_list = MatchBettingGroup.objects.filter(
        Q(group__id=group_id),
        Q(status=MatchBettingGroup.active)
    )

    tournament_list = group.owning_group_tournaments.all()

    # Nd to create separate qurysets for different tournament statuses and only display active tournaments
    # & tournaments not yet begun
    query = request.GET.get('q')
    current_datetime = timezone.now()
    three_months = timezone.timedelta(days=90)

    if query:
        latest_game_list = latest_game_list.filter(
            ~Q(match__status=Match.finished),
            ~Q(match__status=Match.finished_not_confirmed),
            ~Q(match__status=Match.finished_confirmed),
            ~Q(match__status=Match.finished_paid),
            Q(match__tournament__videogame__name__iexact=query)
        ).order_by('match__start_datetime')[:12]

        tournament_list = tournament_list.filter(videogame__name__iexact=query)

    else:
        latest_game_list = latest_game_list.filter(
            ~Q(match__status=Match.finished),
            ~Q(match__status=Match.finished_not_confirmed),
            ~Q(match__status=Match.finished_confirmed),
            ~Q(match__status=Match.finished_paid)
        ).order_by('match__start_datetime')[:12]
        query = False

    upcoming_tournaments = tournament_list.filter(
            Q(start_datetime__gt=current_datetime),
            Q(start_datetime__lt=current_datetime + three_months)
        ).order_by('start_datetime')

    ongoing_tournaments = tournament_list.filter(
            Q(start_datetime__lt=current_datetime),
            Q(end_datetime__gt=current_datetime)
        ).order_by('start_datetime')[:12]

    ongoing_tournaments1 = ongoing_tournaments[:(-(-len(ongoing_tournaments)//2))]
    ongoing_tournaments2 = ongoing_tournaments[(-(-len(ongoing_tournaments)//2)):]

    completed_tournaments = tournament_list.filter(
            Q(start_datetime__lt=current_datetime),
            Q(end_datetime__lt=current_datetime),
            Q(end_datetime__gt=current_datetime - three_months)
        ).order_by('start_datetime')
    context = {
        'group': group,
        'latest_game_list': latest_game_list,

Groups/templates/groups/group_admin/admin_add_game.html
{% include 'datetime_css_js.html' %}

<div class="betting-title rounded row" style=" margin-right: 0px; margin-left: 0px; margin-bottom: 1rem">
    <div class="col-sm-8">
        <h4 class="display-4" style="font-size: 2.3rem;font-weight: 500; margin-bottom: .25rem;">Create Game </h4>
    </div>
    <div class="col-sm-4">

    </div>
</div>

<form method='POST' style="padding-left: 0.5rem;" action='{% url "groups:adminPageAddGames" group_id=group.id %}'>{% csrf_token %}
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Tournament:
        </p>
        <p class="info">
            Names must be unique to your group and can only contain standard letters and numbers
        </p>
    </div>
    <div class="col-sm-4">
        <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
            <div class="form-group">
                <select name="tournament_id" class="form-control" id="exampleFormControlSelect1">
                  {% for tournament in group.owning_group_tournaments.all %}
                    <option value="{{ tournament.id }}">{{ tournament.name }}</option>
                  {% endfor %}
                </select>
            </div>
        </div>
    </div>
</div>
    <div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Users:
        </p>
        <p class="info">
            This is the amount of points member will gain per day.
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%); z-index: 1; width: 100%;">
                <div class="form-group" style="width: 100%;">
                    <select name="user_a" class="form-control" id="exampleFormControlSelect1" style="width: 35%; display: inline-block;">
                      {% for wallet in group.groups_wallet.all %}
                        <option value="{{ wallet.id }}">{{ wallet.profile.user }}</option>
                      {% endfor %}
                    </select>
                vs

                    <select name="user_b" class="form-control" id="exampleFormControlSelect1" style="width: 35%; display: inline-block;">
                      {% for wallet in group.groups_wallet.all %}
                        <option value="{{ wallet.id }}">{{ wallet.profile.user }}</option>
                      {% endfor %}
                    </select>
                </div>
            </div>
    </div>
</div>

<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Start Date:
        </p>
        <p class="info">
            Selecting this requires new members to be invited (cannot join through the group page).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input class="datepicker form-control" name="game_start_datetime" id="GameStartDatetime">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Expected Duration:
        </p>
        <p class="info">
            Selecting this allows any member of the group to send invites (If unselected only admins will be able to send invites).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input type="number" class="form-control" name="game_duration" id="GameEndDatetime">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Twitch URL:
        </p>
        <p class="info">
            This is the background colour behind the group name at the top of the page. By default this is white.
        </p>
    </div>
    <div class="col-sm-4">
            <div id="div_id_colour" class="control-group" style="position: absolute; top: 50%; transform: translateY(-50%);">
                <div class="form-check">
                    <input type="text" class="form-control" name="twitch_url" required id="twitch_url"/>
                </div>
            </div>
    </div>
</div>

<div class="row" style="margin-bottom: 1rem;">
    <div class="col-sm-12" style="text-align: center">
        <button class="btn btn-primary" style="width: 30%; display: inline-block;">Save</button>
    </div>
</div>
</form>

<script>
    $('#GameStartDatetime').bootstrapMaterialDatePicker({ format : 'HH:mm - DD/MM/YYYY' });
</script>

Groups/templates/groups/group_admin/admin_add_tournament.html
{% include 'datetime_css_js.html' %}

<div class="betting-title rounded row" style=" margin-right: 0px; margin-left: 0px; margin-bottom: 1rem">
    <div class="col-sm-8">
        <h4 class="display-4" style="font-size: 2.3rem;font-weight: 500; margin-bottom: .25rem;">Create Tournament </h4>
    </div>
    <div class="col-sm-4">

    </div>
</div>

<form method='POST' style="padding-left: 0.5rem;" action='{% url "groups:adminPageAddTournament" group_id=group.id %}'>{% csrf_token %}
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Tournament Name:
        </p>
        <p class="info">
            Names must be unique to your group and can only contain standard letters and numbers
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
                <input type="text" name="tournament_name" class="form-control" id="TournamentNameInput" placeholder="Enter Name Here">
            </div>
    </div>
</div>
    <div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Videogame:
        </p>
        <p class="info">
            This is the amount of points member will gain per day.
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%); z-index: 1;">
                <div class="form-group">
                    <select name="videogame_id" class="form-control" id="exampleFormControlSelect1">
                      {% for videogame in videogames %}
                        <option value="{{ videogame.id }}">{{ videogame.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
            </div>
    </div>
</div>

<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Start Date:
        </p>
        <p class="info">
            Selecting this requires new members to be invited (cannot join through the group page).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input class="date form-control" name="tournament_start_date" id="TournamentStartDate">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            End Date:
        </p>
        <p class="info">
            Selecting this allows any member of the group to send invites (If unselected only admins will be able to send invites).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input type="text" class="date form-control" name="tournament_end_date" id="TournamentEndDate">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Twitch URL:
        </p>
        <p class="info">
            This is the background colour behind the group name at the top of the page. By default this is white.
        </p>
    </div>
    <div class="col-sm-4">
            <div id="div_id_colour" class="control-group" style="position: absolute; top: 50%; transform: translateY(-50%);">
                <div class="form-check">
                    <input type="text" class="form-control" name="twitch_url" required id="twitch_url"/>
                </div>
            </div>
    </div>
</div>

<div class="row" style="margin-bottom: 1rem;">
    <div class="col-sm-12" style="text-align: center">
        <button class="btn btn-primary" style="width: 30%; display: inline-block;">Save</button>
    </div>
</div>
</form>

<script>
    $('#TournamentStartDate').bootstrapMaterialDatePicker({ format : 'HH:mm - DD/MM/YYYY' });
    $('#TournamentEndDate').bootstrapMaterialDatePicker({ format : 'HH:mm - DD/MM/YYYY' });
</script>

Groups/templates/groups/group_admin/admin_general_options.html
<form method='POST' action='{% url "groups:adminPage" group_id=group.id %}'>{% csrf_token %}

    <div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Daily Payout:
        </p>
        <p class="info">
            This is the amount of points member will gain per day.
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
                  <input name="daily_payout" type="number" class="form-control" aria-label="Amount (to the nearest pound)" min="0.01" step="0.01" max="10000" placeholder="5.00" id="daily_payout" required>
            </div>
    </div>
</div>

<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Invite Only:
        </p>
        <p class="info">
            Selecting this requires new members to be invited (cannot join through the group page).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input class="form-check-input" type="checkbox" name="invite_only" value="True" id="InviteOnlyCheckbox" style="height: 25px; width: 25px;">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Allow Members to Send Invites:
        </p>
        <p class="info">
            Selecting this allows any member of the group to send invites (If unselected only admins will be able to send invites).
        </p>
    </div>
    <div class="col-sm-4">
            <div class="form-check" style="position: absolute; top: 50%; transform: translateY(-50%);">
              <input class="form-check-input" type="checkbox" name="members_can_invite" value="True" id="MembersCanInviteCheckbox" style="height: 25px; width: 25px;">
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1.25rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Change group header background colour:
        </p>
        <p class="info">
            This is the background colour behind the group name at the top of the page. By default this is white.
        </p>
    </div>
    <div class="col-sm-4">
            <div id="div_id_colour" class="control-group" style="position: absolute; top: 50%; transform: translateY(-50%);">
                <div class="controls">
                    <input type="text" name="header_background_colour" class="jscolor form-control" value="ffffff" maxlength="7" required id="header_background_colour" style="width: 90%;"/>
                </div>
            </div>
    </div>
</div>
<div class="row" style="border-bottom: 1px solid #c3c3c3; margin-bottom: 1rem;">
    <div class="col-sm-8">
        <p class="font-weight-bold">
            Change group header text colour:
        </p>
        <p class="info">
            This is the text colour of the group name at the top of the page. By default this is black.
        </p>
    </div>
    <div class="col-sm-4">
            <div id="div_id_colour" class="control-group" style="position: absolute; top: 50%; transform: translateY(-50%);">
                <div class="controls">
                    <input type="text" name="header_text_colour" class="jscolor form-control" value="000000" maxlength="7" required id="header_text_colour" style="width: 90%;"/>
                </div>
            </div>
    </div>
</div>
<div class="row" style="margin-bottom: 1rem;">
    <div class="col-sm-12" style="text-align: center">
        <button class="btn btn-primary" style="width: 30%; display: inline-block;">Save</button>
    </div>
</div>
</form>

<script>
    // Set fields to database values
    $("#daily_payout").attr("value","{{ group.daily_payout }}");
    if ("{{ group.private }}" == "True") {
        $("#InviteOnlyCheckbox").attr("checked","checked");
    };
    if ("{{ group.members_can_inv }}" == "True") {
        $("#MembersCanInviteCheckbox").attr("checked","checked");
    };
    console.log("{{ group.private }}, {{ group.members_can_inv }}")
    $("#header_background_colour").attr("value","{{ group.header_background_colour }}");
    $("#header_text_colour").attr("value","{{ group.header_text_colour }}");

</script>

Groups/templates/groups/group_admin/admin_members.html
<div class="row">

    <div class="col-sm-6">
        <p class="info">
            Add, remove or promote members.
        </p>
    </div>
    <div class="col-sm-6">

    </div>
</div>